// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalRestDemo.DAL;

#nullable disable

namespace MinimalRestDemo.Migrations
{
    [DbContext(typeof(UserCourseDemoDbContext))]
    [Migration("20220313150908_Test")]
    partial class Test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MinimalRestDemo.DAL.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserCourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserCourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MinimalRestDemo.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserCourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserCourseId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MinimalRestDemo.DAL.Models.UserCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("UserCourses");
                });

            modelBuilder.Entity("MinimalRestDemo.DAL.Models.Course", b =>
                {
                    b.HasOne("MinimalRestDemo.DAL.Models.UserCourse", null)
                        .WithMany("Courses")
                        .HasForeignKey("UserCourseId");
                });

            modelBuilder.Entity("MinimalRestDemo.DAL.Models.User", b =>
                {
                    b.HasOne("MinimalRestDemo.DAL.Models.UserCourse", null)
                        .WithMany("Users")
                        .HasForeignKey("UserCourseId");
                });

            modelBuilder.Entity("MinimalRestDemo.DAL.Models.UserCourse", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
